.github/workflows/ci.yaml

Fixes DEV release tag to be `<next prod release version>-dev.<build number>`

fix: Dev release tags

---

.github/workflows/ci.yaml
tests_integration/test_main.py

- Issue:
Adding integration test for resource access flow
Adding integration test for resource access flow
1. Added environmental variable "TWINGATE_TEST_PRINCIPAL_ID" as requirement for testing as resourceAccess requires the value
2. Added environtal variable "TWINGATE_REMOTE_NETWORK_ID" as requirement for testing as this is required by the operator

test: resourceaccess integration testing

---

.github/workflows/ci.yaml
Makefile
app/api/client.py
poetry.lock
pyproject.toml

- Removed `pydocstyle`
- Added `pydocstyle` ruff rules (`D`)
- Moved `S101` ignore to be specific to test files

build: Replace pydocstyle with ruff

---

pyproject.toml

- Issue:
- Added setting that tells `semantic-release` to patch when seeing `chore` or `build` commits:
```
patch_tags = ["fix", "perf", "chore", "build"]
```
Say we release a version `1.0.0` and now dependabot merges a dependency update (`chore` PR) it should be released 
as `1.0.1-dev.<build>` because its newer than `1.0.0`.
Today it gets released as `1.0.0-dev.<build>` which is considered older than `1.0.0`

fix: chore, build changes should change patch

---

app/crds.py
app/handlers/handlers_connectors.py
deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
tests_integration/test_connector_flows.py
tests_integration/test_crds_connector.py

- Issue: #57 
Allow customizing `logLevel` via the `TwingateConnector` CRD spec.
- Modified CRD
- Modified CRD Python model
- Modified `get_connector_pod`

feat: Allow customizing connector logLevel

---

app/tests/test_settings.py

Should use pytest fixtures and not the `@patch` decorator

fix: test_remote_network_name_gets_network_id

---

app/handlers/handlers_connectors.py
app/handlers/handlers_resource.py
app/handlers/handlers_resource_access.py
app/handlers/tests/test_handlers_connector.py
app/handlers/tests/test_handlers_resource.py
app/handlers/tests/test_handlers_resource_access.py
main.py

`gql.Client` is not thread-safe so we cant use it as singleton
https://github.com/graphql-python/gql/issues/314

fix: gql.Client can't be singleton as its not thread-safe

---

app/handlers/handlers_connectors.py

Resolves #102 
Add relevant `securityContext` settings to run connector `0.163.0` as non root and allow running under restricted pod security policy.

feat: Add relevant security context to run as non root

---

main.py

Disable access logs to healthcheck - it just adds a ton of useless logs

fix: Disable healthcheck access logs

---

app/api/client_resources.py
app/api/tests/test_client_resources.py
app/crds.py
pyproject.toml
tests_integration/test_resource_flows.py

- Issue: #145 
Fixed `Resource.is_matching_spec` - it was not comparing `protocols` properly so would always return false causing `twingate_resource_sync` to always think there's a drift and issue an update call

fix: Fix resource `protocols` diffing and serialization

---

app/api/client.py
app/api/client_connectors.py
app/api/client_resources.py
app/api/exceptions.py
app/api/tests/test_client_resources.py
app/api/tests/test_connectors.py

Fix #159 
- Treat delete mustation of an entity no longer in Twingate as a success

fix: Deleting an item already deleted on Twingate Admin should not fail

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py
tests_integration/test_connector_flows.py

- Issue: #161 
On TwingateConnector resume event check if pod exists

fix: twingate connector doesnt handle pod deletion on resume

---

app/handlers/handlers_connectors.py

- Added return status to `twingate_connector_resume` 
- Added log when pod requires recreation

fix: Add status and logs to `twingate_connector_resume`

---

app/api/client_resources.py
app/api/tests/test_connectors.py

Pydantic deprecated `.dict()` for `.model_dump()`

chore: Pydantic deprecated .dict() for .model_dump()

---

app/handlers/handlers_resource_access.py
app/handlers/tests/test_handlers_resource_access.py

Fixes #174 
Limit the update scope of `twingate_resource_access_update` to just the `spec` field

fix: Limit twingate_resource_access_update scope to spec

---

app/handlers/handlers_connectors.py
app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_connector.py
app/handlers/tests/test_handlers_resource.py

Fixes #173 
`twingate_resource_update` should only care when `spec` updates

fix: Reduce update scope for `twingate_resource_update`

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py
tests_integration/test_connector_flows.py

`twingate_connector_recreate_pod` should remove the `LABEL_CONNECTOR_POD_DELETED` pod after its done

fix: LABEL_CONNECTOR_POD_DELETED isnt set to false after pod recreated

---

app/handlers/handlers_connectors.py

`k8s_force_delete_pod` was not deleting pod finalizers.
`[]` makes it merge the value with existing value instead of deleting it.

fix: Fix k8s_force_delete_pod finalizers removal

---

app/crds.py
app/tests/test_crds_resource.py
deploy/twingate-operator/crds/twingate.com.twingateresources.yaml
tests_integration/test_connector_flows.py
tests_integration/test_crds_resource.py

- Issue: #192 
- Fixed minimum port value - should be 1 not zero
- Allow `RESTRICTED` ports to be empty list which means "block all"
Also manually tested adding this resource:
```
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
name: foo
spec:
name: Foo
address: foo.default.cluster.local
protocols:
allowIcmp: true
tcp:
policy: RESTRICTED
ports:
- end: 8080
start: 8080
udp:
policy: RESTRICTED
ports: []
```
result:

fix: Resource restricted policy should allow empty ports

---

Makefile
app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py
tests_integration/test_connector_flows.py

Tests the fix of #189 by adding `test_connector_flows_pod_migration_from_older_pod_with_finalizers`.
We create a connector, patch the pod with a finalizer and wrong version annotation and make sure the reconciler is able to delete and recreate it.

chore: Integration test for old pod migration

---

.github/dependabot.yml
.github/workflows/ci.yaml
go.mod

- Setup dependabot to update Go dependenciesa
- Upgraded Go to 1.22.0

chore: Upgrade Go to 1.22.0 and setup dependabot

---

app/handlers/handlers_connectors.py
app/tests/test_crds_connector.py

Fixes #216 
Allow `env` to be defind in `containerExtra` and merge it with the pod `env` we set in our code

fix: Allow env to be defined in containerExtra

---

deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
tests_integration/test_connector_flows.py

Fixes #215 
- Make `containerExtra` and `podExtra` mutable
The refactor in `TwingateConnector` reconciliation (https://github.com/Twingate/kubernetes-operator/pull/180) made this possible out of the box because we delete the pod and recreate it anyway on any update

feat: Make TwingateConnector's containerExtra and podExtra mutable

---

deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
tests_integration/test_crds_connector.py

Fixes #214 
Added `TwingateConnector` CRD validation that forces defining `repository` if `provider` is `google`

fix: Add validation for TwingateConnector when provider is “google”

---

app/crds.py
app/handlers/handlers_connectors.py
deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
examples/connector.yaml
tests_integration/test_connector_flows.py

Fixes #217 
- Add `podAnnotations` to `TwingateConnector` CRD
- propagate annotations to created pod

feat: TwingateConnector - allow defining extra pod annotations with `podAnnotations`

---

app/crds.py
app/handlers/handlers_connectors.py
deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml

Resolves #232
Added `sidecarContainers` to allow injecting sidevcars to connector pods
Example on prometheus operator: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3853

feat: Add TwingateConnector sidecarContainers prop

---

app/crds.py
app/handlers/handlers_connectors.py
deploy/twingate-operator/Chart.yaml
deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
tests_integration/test_crds_connector.py

Resolves #238 
- Added `logAnalytics` property to `TwingateConnector` (default to `true`)
- If `logAnalytics` is true we add `TWINGATE_LOG_ANALYTICS=v2` env var to connector pod

feat: Added TwingateConnector `logAnalytics` flag

---

app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_resource.py

Resolves #245 
- If `TwingateResource` created with `id` dont attempt to create it

feat: Ability to import existing twingate resources

---

app/handlers/handlers_resource_access.py
app/handlers/tests/test_handlers_resource_access.py
tests_integration/test_resource_flows.py

Resolves #239 
- create\update\sync handler were all basically doing the same thing - removed redundant code and just use a single function
- When `principalExternalRef` is used - cache the resulting `principalId` on creation and use that value going forward

feat: Don’t query for principal external ref once we have the id

---

app/handlers/handlers_services.py
app/handlers/tests/test_handlers_services.py
tests_integration/test_service_flows.py

Related to comments mentioned in #271 
- Allow overriding default resource name with a `twingate.com/resource-name` annotation

feat: Allow defining custom resource Name for annotated service resource

---

app/handlers/handlers_resource_access.py
app/handlers/tests/test_handlers_resource_access.py

Fix #287 
- Remove ownerReference for `TwingateResourceAccess` 
If a resource that the access object is referencing gets removed the access object shouldnt get deleted as well but remain there and log errors on reconciliation

fix: Remove TwingateResourceAccess ownerReference

---

app/handlers/handlers_connectors.py
deploy/twingate-operator/values.yaml

Resolves #102 
When testing setting pod-security to restricted
```
kubectl label --dry-run=server --overwrite ns twingate \
pod-security.kubernetes.io/enforce=restricted \
pod-security.kubernetes.io/enforce-version=latest
Warning: existing pods in namespace "twingate" violate the new PodSecurity enforce level "restricted:latest"
Warning: corp-connector-stg-1 (and 1 other pod): seccompProfile
namespace/twingate labeled (server dry run)
```
connectors are missing seccompProfile
Add required 
```
seccompProfile:
type: RuntimeDefault
```

fix: Allow connectors to run under Restricted pod-security policy

---

deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
deploy/twingate-operator/crds/twingate.com.twingateresourceaccesses.yaml
deploy/twingate-operator/crds/twingate.com.twingateresources.yaml

- Issue: #343 
- Remove included explicit definition of `nullable: false` from the CRDs as its the Kubernetes default, and won't be persisted in the representation of the CRD resource.
The goal here is for any gitops flow to not always detect a "drift" or "dirtiness" between what is in code, and what is available via the Kubernetes API.

Removes 'nullable: false' from CRD definitions (as its the default)

---

app/crds.py
app/handlers/handlers_groups.py
app/handlers/handlers_resource_access.py
app/handlers/tests/test_handlers_resource_access.py
app/tests/test_crds_resourceaccess.py
deploy/twingate-operator/crds/twingate.com.twingateresourceaccesses.yaml
tests_integration/test_connector_flows.py
tests_integration/test_crds_resourceaccess.py
tests_integration/test_resource_flows.py

- Issue: #364 
- Added `groupRef` to `TwingateResourceAccess` CRD
- Some improvement to integration test - when re-run from failed, the CI run number doesnt change which caused re-runs to not work. So added better randomization for resource names to allow rerunning
Usage Example:
```
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
name: my-twingate-resource
spec:
name: My K8S Resource
address: my.default.cluster.local
alias: mine.local
---
apiVersion: twingate.com/v1beta
kind: TwingateGroup
metadata:
name: test-group
spec:
name: Test Group
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
name: my-twingate-resource
spec:
resourceRef:
name: my-twingate-resource
groupRef:
name: "test-group"
```

feat: Support referencing TwingateGroup from TwingateResourceAccess

---

app/api/client_resources_access.py
app/api/tests/test_client_resource_access.py

- Issue: #403 
- Handle exception in `resource_access_remove` API call

fix: TwingateResourceAccess deletion fail if resource has been deleted

---

deploy/twingate-operator/templates/clusterrole.yaml

- Issue: TwingateGroup objects cannot be handled by the operator due to missing permissions over the TwingateGroup apis
- Fix operator permissions over twingategroups apis
- apply a twingate group object kind
- operator logs an error about missing permissions to list twingategroups
- the group is not created on twingate side

Fix  clusterrole with permissions over twingategroups objects

---

deploy/test/golden/extraEnvVars.golden.yaml
deploy/test/golden/extraEnvVars.yaml
deploy/twingate-operator/Chart.yaml
deploy/twingate-operator/templates/deployment.yaml
deploy/twingate-operator/values.schema.json
deploy/twingate-operator/values.yaml

Fixes https://github.com/Twingate/kubernetes-operator/pull/487
We've added the feature to allow configuring KOPF using env vars but we also need the chart to support defining custom env vars

fix: Allow extra env vars in the operator's Chart

---

deploy/test/golden/error-too-many-remotenetwork-definitions.golden.yaml
deploy/test/golden/error-too-many-remotenetwork-definitions.yaml
deploy/test/golden/existingRemoteNetworkIdSecret.golden.yaml
deploy/test/golden/existingRemoteNetworkIdSecret.yaml
deploy/twingate-operator/Chart.yaml
deploy/twingate-operator/templates/deployment.yaml
deploy/twingate-operator/values.schema.json
deploy/twingate-operator/values.yaml

Allow fetching remote network idea from an existing Secret object.
- Issue: #122 
Add `existingRemoteNetworkIdSecret` configuration option to fetch the remote network ID from an existing `Secret` object.

feat: Helm chart - Add `existingRemoteNetworkIdSecret`

---

.pre-commit-config.yaml
app/settings.py
poetry.lock
pyproject.toml

Removed `isort` and added it as a ruff rule

chore: Remove `isort` and use `ruff` instead

---

.pre-commit-config.yaml
app/handlers/tests/test_handlers_services.py
poetry.lock
pyproject.toml

- Issue:
- Removed autoflake. We're already using Ruff for that functionality...
- Added FURB, PGH, ASYNC
- Added proper typechecking to `yaml` module

chore: Remove autoflake and use Ruff instead + Extra Ruff rules

---

README.md

**Changes**
This PR fixes a small typo in the README.md file:
- "Helm by **closing** the git repository" → "Helm by **cloning** the git repository"
- Ensures clarity in the installation instructions for users installing via Helm.
**Notes**
N/A (No breaking changes or alternative approaches considered.)

docs: Fix typo 'closing' → 'cloning' in Helm installation section

---

deploy/twingate-operator/crds/twingate.com.twingateconnector.yaml
deploy/twingate-operator/crds/twingate.com.twingategroup.yaml
deploy/twingate-operator/crds/twingate.com.twingateresourceaccesses.yaml
deploy/twingate-operator/crds/twingate.com.twingateresources.yaml

Added category to our objects so that they appear when doing `kubectl get all` but also added a specific twingate category so all our objects appear on `kubectl get twingate`
Example:
```
➜ kubectl get twingate
NAME                                                              ID                         DISPLAY NAME             AGE
twingateconnector.twingate.com/my-connector-auto-updating-image   Q29ubmVjdG9yOjk3MDU1OQ==   nondescript-jackrabbit   18m
twingateconnector.twingate.com/my-connector-fixed-image           Q29ubmVjdG9yOjk3MDU2MA==   icy-orca                 18m
NAME                                 ID                     DISPLAY NAME    AGE
twingategroup.twingate.com/example   R3JvdXA6MzA1NDM5NA==   Example Group   18m
NAME …
```

feat(crds): add categories to CRDs and fix indentation for shortNames to enhance organization and readability in Kubernetes resources

---

tests_integration/test_crds_connector.py

- Remove `integration` test marker on `TestConnectorCRD`

chore: Remove redundant integration test marker

---

.envrc.local.example
DEVELOPER.md
README.md

- Update `.envrc.local.example` to include missing envvar `TWINGATE_TEST_PRINCIPAL_ID`, which is needed to run [`test_resource_flows`](https://github.com/Twingate/kubernetes-operator/blob/c6ec9e2d42fe03023a48d6e6cdc6cac041aeab7f/tests_integration/test_resource_flows.py#L213-L214) locally
- Update `README.md` instructions to include `Provision` permission for Twingate API token
- Update `DEVELOPER.md` 
- Update local development instructions to be clearer
- Fix some minor typos

docs: Improve `DEVELOPER.md` and `README.md` documentations

---

app/api/client_resources.py
app/api/tests/test_client_resources.py
app/crds.py
app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_resource.py
app/settings.py
app/tests/test_crds_resource.py
deploy/test/golden/apikey.golden.yaml
deploy/test/golden/defaultResourceTags.golden.yaml
deploy/test/golden/defaultResourceTags.yaml
deploy/test/golden/existingRemoteNetworkIdSecret.golden.yaml
deploy/test/golden/extraEnvVars.golden.yaml
deploy/test/golden/logVerbosity.golden.yaml
deploy/test/golden/podLabels.golden.yaml
deploy/test/golden/priorityClassName.golden.yaml
deploy/test/golden/remoteNetworkName.golden.yaml
deploy/twingate-operator/templates/deployment.yaml
deploy/twingate-operator/values.schema.json
deploy/twingate-operator/values.yaml

- Add default tags to Twingate Resource based on `TWINGATE_DEFAULT_RESOURCE_TAGS` envvar set on the Operator.
- Refactor Resource client API code

feat: Supporting adding default tags on Twingate Resource

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py

- Issue: https://github.com/Twingate/kubernetes-operator/issues/604
- Add `livenessProbe` and `readinessProbe` to `TwingateConnector.spec.container`
- Set `readOnlyRootFilesystem` in `securityContext` to `True` by default. Also, add `volumes` and `volumeMounts`

feat: Support `livenessProbe`, `readinessProbe` and enhance security by setting `readOnlyRootFilesystem` on `TwingateConnector`

---

app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_resource.py
app/settings.py
deploy/test/golden/defaultResourceTags.golden.yaml
deploy/test/golden/defaultResourceTags.yaml
deploy/twingate-operator/values.schema.json
deploy/twingate-operator/values.yaml

Changed `defaultResourceTags` schema in `values.yaml` to match how labels are defined in k8s - as an object rather than a list of objects. (see example: https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.7.8/_definitions.json#L528)

fix: `defaultResourceTags` to match labels schema

---

app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_resource.py

- A regression bug was introduced when we updated `twingate_resource_update` handler to detect change on the whole object instead of the `spec` field in this [PR](https://github.com/Twingate/kubernetes-operator/commit/e77773d38246bd1352bf6dd6af6271a50d8d13da#diff-dab0a0f836e493ffe8dc057c0f1a4b6c4914c67865f7747b06c0c170068a8075L37-L38). As a result, the `diff` structure is different and needs to be updated to match the new structure.
- Return `success` result when resource is updated in `twingate_resource_sync` handler. This is an improvement for better status logging.

fix: Skip `twingate_resource_update` handler when `spec.id` is added

---

main.py

- Issue: #642 
- Added `client_timeout` setting

fix: Add client_timeout setting to prevent operator disconnect

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py

Reconciler was always calling k8s replace because image if statement was wrong.

fix: Reconciler should only update k8s if there’s drift in image

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py
examples/connector.yaml
tests_integration/test_connector_flows.py

Fixes #651 
- The "reserved" name we use for connector label can't be a well-known name that might be used by user...

fix: Dont use a well known label name as selector

---

app/api/client_resources.py
app/api/tests/test_client_resources.py

- `get_resource` should only return `None` if resource not found not if query is invalid or any other kind of error.
- Returning `None` in case of error can lead to resource_reconciler recreating the resource over and over unecessarily

fix: Get resource should only return None if not found

---

pyproject.toml

https://python-semantic-release.readthedocs.io/en/latest/upgrading/10-upgrade.html#default-configuration-changes
Default used to be `true` and changed to `false` in v10

fix: allow_zero_version should be true

---

app/handlers/handlers_services.py
app/handlers/tests/test_handlers_services.py

Regardless of the k8s namespace the Gateway is deployed on, the `kubernetes` service (represent the API server for in-cluster traffic) is always on the `default` namespace ([doc](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api)).

fix: Always use `kubernetes.default.svc.cluster.local` as the address of a k8s resource

---

app/handlers/handlers_connectors.py
app/handlers/tests/test_handlers_connector.py

Fixes #673 
When upgrading connectors from `Pod` to `Deployment`, the code path using `imagePolicy` was missing a check - it would only check the deployment when the policy's `schedule` is triggered which is usually daily or longer.
This change fixes `twingate_connector_pod_reconciler` to recreate the deployment if it doesnt exist, regardless of the `schedule` value

fix: Pod to Deployment migration doesnt work with imagePolicy

---

app/handlers/handlers_resource.py
app/handlers/tests/test_handlers_resource.py

Optimize `twingate_resource_update` so that it doesnt call API to update the resource unless there was a change in `spec` o `metadata.labels`

fix: Only call resource udate when spec\labels update

---

.github/workflows/release.yaml
.github/workflows/verify-pr.yaml
.github/workflows/vulnerability-monitor.yaml

Potential fix for [https://github.com/Twingate/kubernetes-operator/security/code-scanning/9](https://github.com/Twingate/kubernetes-operator/security/code-scanning/9)
To fix the problem, add a `permissions` block to the `release_prod` job in `.github/workflows/release.yaml`. This block should specify the minimal permissions required for the job. As a starting point, set `contents: read`, which allows the job to read repository contents but not modify them. If the job later requires additional permissions (e.g., to create releases), these can be added as needed. The change should be made directly under the `release_prod` job definition, before the `name` or `runs-on` keys.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: Github Action workflow permissions

---

deploy/twingate-operator/templates/deployment.yaml
deploy/twingate-operator/tests/__snapshot__/default_values_test.yaml.snap
deploy/twingate-operator/tests/deployment_optional_values_test.yaml
deploy/twingate-operator/values.schema.json
deploy/twingate-operator/values.yaml

- Issue: https://github.com/Twingate/kubernetes-operator/issues/719, https://github.com/Twingate/kubernetes-operator/issues/717
- Allow scoping Operator installation on specific namespaces
Currently, Operator will apply `twingate.com/kopf-managed` and `twingate.com/last-handled-configuration` annotations to all Kubernetes services & Twigate CRD across all namespaces. In some cases, we are not supposed to modify the k8s Service. Issue #717 is an example where we are not allowed to edit the `kube-system` namespace of the GKE autopilot cluster.

feat: Allow scoping Operator installation on specific namespaces

---

deploy/twingate-operator/templates/pre-delete-cleanup.yaml
deploy/twingate-operator/tests/__snapshot__/pre-delete-cleanup_test.yaml.snap

Unlike the `bitnami/kubectl` image (replaced in https://github.com/Twingate/kubernetes-operator/pull/768), `rancher/kubectl` image doesn't include a shell so we need to run `kubectl` directly. Currently, the `pre-delete-cleanup` job fails with the following error
```
Failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

fix: Fix `pre-delete-cleanup` job
