- DEVELOPER.md
- README.md
- Issue: #3 
- Added CI\Coveralls\Dockerhub bagdes
- Move developer guide to DEVELOPER.md
> docs: README overhaul

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.md
- .pre-commit-config.yaml
- Issue: #5 
Added issue templates
> chore: Add Issue Templates

- app/api/client_resources.py
- app/api/tests/factories.py
- app/api/tests/test_client_resources.py
- app/crds.py
- app/tests/test_crds.py
- deploy/twingate-operator/crds/twingate.com.twingateresources.yaml
- tests_integration/test_main.py
- Issue: #2 
- Modify CRD to support all possible Resource props
- Modify muattions in API later to support these new props
> feat: Support protocol restrictions on twingateresource

- main.py
- Added type annotations to startup\cleanup functions
- Customized Kopf's [persistence settings](https://kopf.readthedocs.io/en/stable/configuration/#change-detection) - sa,e as the default but changed the prefixes from `kopf.zalando.org` to `operator.twingate.com`
This change is important to avoid collision in the off chance user has 2 operators that were written using `kopf`.
Its not a concern for our own CRDs but if we ever integrate with built-in objects (service\ingress\pod) it might.
See example of resource applied in K8s post this change:
```
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"twingate.com/v1beta","kind":"TwingateResource","metadata":{"annotations":{},"name":"my-twingate-res …
```
> fix: Change persistence settings to use Twingate namespace

- app/crds.py
> fix: ResourceAccessSpec.get_resource_ref_object fetching wrong version

- main.py
Simplify operator's annotation to just be under `twingate.com` instead of 1`operator.twingate.com`
> fix: change persistence layer - operator.twingate.com to just twingate.com

- DEVELOPER.md
Improve developers docs:
- More details on how to setup dev environment
- Details on how to setup PyCharm
> docs: Improve development docs

- app/tests/test_crds.py
Removed `mock_get_namespaced_custom_object` not being used
> test: remove unused fixture

- scripts/minikube-smoketests.sh
Fix version limit in minikube.
Added it because there was an RBAC issue with latest minikube release
> Fix: minikube RBAC

- Dockerfile
- scripts/minikube-smoketests.sh
> Fix: CVE-2023-5752 - always use latest pip

- .pre-commit-config.yaml
- app/api/client.py
- app/api/client_remote_networks.py
- app/api/tests/test_client_remote_networks.py
- app/settings.py
- deploy/golden_test.go
- deploy/test/golden/error-missingRemoteNetwork-name-or-id.golden.yaml
- deploy/test/golden/error-missingRemoteNetwork-name-or-id.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/test/golden/remoteNetworkName.yaml
- deploy/twingate-operator/templates/deployment.yaml
- deploy/twingate-operator/values.schema.json
- deploy/twingate-operator/values.yaml
When configuring the operator, allow setting the remote network as a reference by name.
> feat: Allow setting remote network by name

- pyproject.toml
Remove dependabot PRs from changelog
> build: Make CHANGELOG generation nicer

- deploy/test/golden/apikey.golden.yaml
- deploy/test/golden/existingAPIKeySecret.golden.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/twingate-operator/Chart.yaml
- deploy/twingate-operator/values.yaml
Add `seccompProfile` to pod security context by default
> feat: Add seccompProfile by default

- deploy/test/golden/priorityClassName.golden.yaml
- deploy/test/golden/priorityClassName.yaml
- deploy/twingate-operator/Chart.yaml
- deploy/twingate-operator/templates/deployment.yaml
- deploy/twingate-operator/values.yaml
Fixes #121 
Adds `priorityClassName` as configurable value to `values.yaml`
> feat: Add support for priorityClassName

- deploy/test/golden/podLabels.golden.yaml
- deploy/test/golden/podLabels.yaml
- deploy/twingate-operator/Chart.yaml
- deploy/twingate-operator/templates/deployment.yaml
- deploy/twingate-operator/values.yaml
Fixes #120 
Add `podLabels` to `values.yaml` allowing to define additional labels to set on the pod
> feat: Add podLabels

- app/handlers/handlers_connectors.py
- app/handlers/tests/test_handlers_connector.py
- tests_integration/test_connector_flows.py
- tests_integration/utils.py
Fixes #130 
When `image` property changes re-apply changes to the pod
> fix: Added `twingate_connector_image_update` to handle `image` updates

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .tool-versions
Upgrade to latest Poetry.
See https://python-poetry.org/history/
> chore: Upgrade Poetry to latest 1.8.2

- app/api/tests/conftest.py
- app/handlers/handlers_connectors.py
- app/handlers/handlers_resource.py
- app/version_policy_providers/__init__.py
- pyproject.toml
- tests_integration/test_connector_flows.py
> chore: Add more Ruff linters

- .tool-versions
- deploy/test/golden/apikey.golden.yaml
- deploy/test/golden/existingAPIKeySecret.golden.yaml
- deploy/test/golden/logVerbosity.golden.yaml
- deploy/test/golden/logVerbosity.yaml
- deploy/test/golden/podLabels.golden.yaml
- deploy/test/golden/priorityClassName.golden.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/twingate-operator/Chart.yaml
- deploy/twingate-operator/templates/deployment.yaml
- deploy/twingate-operator/values.schema.json
- deploy/twingate-operator/values.yaml
- Added `twingateOperator.logVerbosity` to helm chart's `values.yaml`
> feat: Add ability to customize kopf logging level

- .pre-commit-config.yaml
> chore: Pre-commit updates

- app/handlers/handlers_services.py
- app/handlers/tests/test_handlers_services.py
- app/tests/test_utils.py
- app/utils.py
- deploy/test/golden/apikey.golden.yaml
- deploy/test/golden/existingAPIKeySecret.golden.yaml
- deploy/test/golden/logVerbosity.golden.yaml
- deploy/test/golden/podLabels.golden.yaml
- deploy/test/golden/priorityClassName.golden.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/twingate-operator/templates/clusterrole.yaml
- tests_integration/test_service_flows.py
Fixes #269 
- Operator annotation values need to be converted to the right type
- Added missing permissions to cluster role
> fix: using the operator with annotations have some problems

- app/api/tests/test_client_connectors.py
- app/api/tests/test_client_resources.py
- app/handlers/handlers_services.py
- app/handlers/tests/test_handlers.py
- app/handlers/tests/test_handlers_resource_access.py
- app/handlers/tests/test_handlers_services.py
- app/version_policy_providers/tests/test_base.py
- Added safety tests that make sure timer functions are not too short
- Misc. tests
> chore: Increase test coverage

- app/crds.py
- app/handlers/handlers_groups.py
- app/handlers/tests/conftest.py
- app/handlers/tests/test_handlers_group.py
- app/tests/test_crds_resourceaccess.py
> test: More tests for TwingateGroup Handlers

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .tool-versions
> feat: Upgrade to Python 3.12.8

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .tool-versions
- deploy/test/golden/apikey.golden.yaml
- deploy/test/golden/existingAPIKeySecret.golden.yaml
- deploy/test/golden/existingRemoteNetworkIdSecret.golden.yaml
- deploy/test/golden/extraEnvVars.golden.yaml
- deploy/test/golden/logVerbosity.golden.yaml
- deploy/test/golden/podLabels.golden.yaml
- deploy/test/golden/priorityClassName.golden.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/twingate-operator/Chart.yaml
- deploy/twingate-operator/values.yaml
- go.mod
- Issue: #556 
Add appVersion to chart when releasing prod
> feat: Add app-version to chart when releasing prod

- deploy/twingate-operator/crds/twingate.com.twingateresourceaccesses.yaml
Added\improved TwingateResourceAccess CRD descriptions
> docs: Improve TwingateResourceAccess CRD descriptions

- main.py
See KOPF issue https://github.com/nolar/kopf/issues/1120
> fix: set server_timeout to 5 minutes to resolve change detection issue

- main.py
- Raise `RuntimeException` if failed to load settings
> fix: Operator should halt if settings are invalid

- deploy/test/golden/apikey.golden.yaml
- deploy/test/golden/defaultResourceTags.golden.yaml
- deploy/test/golden/existingAPIKeySecret.golden.yaml
- deploy/test/golden/existingRemoteNetworkIdSecret.golden.yaml
- deploy/test/golden/extraEnvVars.golden.yaml
- deploy/test/golden/logVerbosity.golden.yaml
- deploy/test/golden/podLabels.golden.yaml
- deploy/test/golden/priorityClassName.golden.yaml
- deploy/test/golden/remoteNetworkName.golden.yaml
- deploy/twingate-operator/templates/clusterrole.yaml
- Operator should have full control on `twingate.com` resources. This will make us future proof as we add features and resources
> fix: update operator ClusterRole permissions for twingate.com apiGroup

- deploy/twingate-operator/crds/twingate.com.twingateresourceaccesses.yaml
> fix: update CRD schema to set properties to null for oneOf conditions to ensure proper validation
